name: Main Workflow
on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  workflow_dispatch:
 
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
    
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Title of PR
      env:
          TITLE: ${{ github.event.pull_request.title }}
          NUMERO: ${{github.event.inputs.pullRequestNumber }}
      run: echo The Title of your PR is $TITLE
           echo The Number of your PR is $NUMERO
  
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: juliangruber/approve-pull-request-action@v2
      with:
        pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
      
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Example workflow using Snyk
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  
